# Generated by Django 6.0.3 on 2026-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='flow_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='source_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='total_packets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='prediction',
            field=models.CharField(max_length=20),
        ),
    ]
