# Generated by Django 5.1.7 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection', '0002_threatlog_flow_duration_threatlog_source_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_traffic', models.IntegerField(default=0)),
                ('attacks_detected', models.IntegerField(default=0)),
                ('benign_traffic', models.IntegerField(default=0)),
                ('blocked_ips', models.JSONField(default=list)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
